### ISSUE TITLE
Documentation - inconsistent naming

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/cheminformatics-microservice#341]
Documentation inconsistently names the service Cheminformatics Micro Service, CPM, and Cheminformatics Python Microservice. I strongly suggest fully eliminating any references with CPM. We don't need more 3 letter acronyms in this field. Further, the "Python" in the title is a bit misleading since there are several non-Python services wrapped.

- [x] Update GitHub repo name / links
- [x] Update logo
- [x] Update links
- [x] Update manuscript
- [x] Update documentation
- [x] Update Docker Hub and deployment workflows
- [x] repo-helm-charts
- [x] #392
- [ ] Cross check everything again

**Comment by JonasSchaub** [comment]
I have updated the manuscript
