### ISSUE TITLE
Handling invalid input in a consistent and logical way

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/cheminformatics-microservice#344]
Handling invalid input in a consistent and logical way not only in this specific convert/Mol2D function, but in all other functions exposed by the API before publishing the paper.

Also, if an invalid toolkit argument value is provided, for example, zzz, then error 422 is returned, which does make sense. However, if an invalid SMILES string (for example, xxxx) is supplied as the method argument, the method still returns the ‘success’ code 200, but the result contains the following literal string: *‘Error reading SMILES string, check again.’* This is definitely not good, because the client code would have no way of knowing that the operation has failed and may attempt to use the ‘Error reading SMILES string, check again.’ string downstream as if it were a valid CTab/molfile encoding of a molecule. The developers of the API should keep in mind that, in general, results of API calls are meant to be processed by machines, and not intended to be read and interpreted by humans, so consistent and logical error handling is very important for any type of computational service meant to be integrated into a larger system.

**Comment by NishaSharma14** [comment]
https://dev.api.naturalproducts.net/latest/docs#/chem/classyfire_classify_chem_classyfire_classify_get
https://dev.api.naturalproducts.net/latest/docs#/chem/tanimoto_similarity_chem_tanimoto_get
