### ISSUE TITLE
Error handling in tool module

### ISSUE THREAD

**Issue by NishaSharma14** [Steinbeck-Lab/cheminformatics-microservice#379]
- [ ] #386
- [x] #387
- [x] #388

<img width="1081" alt="image" src="https://github.com/Steinbeck-Lab/cheminformatics-microservice/assets/54287612/5ccf51c0-b9e6-4304-b34f-925535f9c042">

<img width="1006" alt="image" src="https://github.com/Steinbeck-Lab/cheminformatics-microservice/assets/54287612/cbb82fa9-0d40-4ca9-b46e-51ec8ec326a2">

**Comment by CS76** [comment]
Closing this now  - only issue needs to be resolved #386
