### ISSUE TITLE
Swagger doc - `tools/remove-sugar` endpoint gives an error as "Error generating SMILES" for the first example.

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/cheminformatics-microservice#386]

**Comment by JonasSchaub** [comment]
My guess is that this is a general problem. The error seems to occur whenever you give it a molecule that consists of sugars completely (e.g. Glucose "C(C1C(C(C(C(O1)O)O)O)O)O"). The SRU returns an empty IAtomContainer object in this case which seems to cause troubles down the line. You could check and treat this using IAtomContainer.isEmpty().

If you would like me to take care of this, it would be nice if someone could guide me on how to set the project up locally and how to push changes correctly.

**Comment by CS76** [comment]
Thanks @JonasSchaub. This is resolved now  - https://github.com/Steinbeck-Lab/cheminformatics-microservice/pull/393

**Comment by JonasSchaub** [comment]
We have the same problem with the other two sugar removal routines.

**Comment by CS76** [comment]
https://github.com/Steinbeck-Lab/cheminformatics-microservice/pull/395
